apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["statefulset:default:tcpserver-stateful"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: 2018-07-26T02:20:19Z
  name: tcpserver-stateful-loadbalancer
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: statefulset
    name: tcpserver-stateful
    uid: 7171b9e3-907a-11e8-83c3-107b447cee8e
  resourceVersion: "4129885"
  selfLink: /api/v1/namespaces/default/services/tcpserver-stateful-loadbalancer
  uid: 718302a8-907a-11e8-83c3-107b447cee8e
spec:
  clusterIP: 10.43.61.84
  externalTrafficPolicy: Cluster
  ports:
  - name: 20352tcp203533
    nodePort: 32683
    port: 20353
    protocol: TCP
    targetPort: 20352
  selector:
    workload.user.cattle.io/workloadselector: statefulSet-default-tcpserver-stateful
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
