apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["statefulset:default:tcpserver-stateful"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: 2018-07-26T02:20:20Z
  name: tcpserver-stateful
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: statefulset
    name: tcpserver-stateful
    uid: 7171b9e3-907a-11e8-83c3-107b447cee8e
  resourceVersion: "4129892"
  selfLink: /api/v1/namespaces/default/services/tcpserver-stateful
  uid: 71b06b6f-907a-11e8-83c3-107b447cee8e
spec:
  clusterIP: 10.43.199.254
  ports:
  - name: 20352tcp203533-tcpserver-stateful
    port: 20352
    protocol: TCP
    targetPort: 20352
  selector:
    workload.user.cattle.io/workloadselector: statefulSet-default-tcpserver-stateful
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
